// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FqwGgIplgrHVN7O4gejmKLhOfheGLig',
    appId: '1:1007954381387:web:82d390217ff197fd271bce',
    messagingSenderId: '1007954381387',
    projectId: 'firstproject-e011d',
    authDomain: 'firstproject-e011d.firebaseapp.com',
    storageBucket: 'firstproject-e011d.firebasestorage.app',
    measurementId: 'G-49DQ8745S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71fk4y3aMN1_CQcep-MHJd7eRSpWdbic',
    appId: '1:1007954381387:android:1daff68b2b0f84b6271bce',
    messagingSenderId: '1007954381387',
    projectId: 'firstproject-e011d',
    storageBucket: 'firstproject-e011d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCI27sjJoz5vqOUr_tgudXG-Qa20ZI-k',
    appId: '1:1007954381387:ios:f3b6feca6e795cfc271bce',
    messagingSenderId: '1007954381387',
    projectId: 'firstproject-e011d',
    storageBucket: 'firstproject-e011d.firebasestorage.app',
    iosBundleId: 'com.simrika.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrCI27sjJoz5vqOUr_tgudXG-Qa20ZI-k',
    appId: '1:1007954381387:ios:4fa09f74fabdb0cd271bce',
    messagingSenderId: '1007954381387',
    projectId: 'firstproject-e011d',
    storageBucket: 'firstproject-e011d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FqwGgIplgrHVN7O4gejmKLhOfheGLig',
    appId: '1:1007954381387:web:b4bb751aaceff97a271bce',
    messagingSenderId: '1007954381387',
    projectId: 'firstproject-e011d',
    authDomain: 'firstproject-e011d.firebaseapp.com',
    storageBucket: 'firstproject-e011d.firebasestorage.app',
    measurementId: 'G-MCVFY82479',
  );
}
